package com.superplanner.gateway

import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonNull
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive

@Serializable data class NaturalLanguageRequest(val schemaVersion:String="1", val message:String, val context:AiProposalContext=AiProposalContext())
@Serializable data class ExplanationRequest(val schemaVersion:String="1", val question:String, val evidence:List<String> = emptyList())
@Serializable data class CommandRequest(val schemaVersion:String="1", val message:String, val context:AiProposalContext=AiProposalContext())
@Serializable data class InsightRequest(val schemaVersion:String="1", val evidence:List<String> = emptyList(), val sampleSize:Int=0)
@Serializable data class PreferenceRequest(val schemaVersion:String="1", val observations:List<String> = emptyList())
@Serializable data class ScenarioRequest(val schemaVersion:String="1", val question:String, val context:AiProposalContext=AiProposalContext())
@Serializable data class NextActionCandidate(val id:String,val durationMinutes:Int?=null,val preparationMinutes:Int?=null,val travelMinutes:Int?=null,val priority:Int?=null,val dependenciesSatisfied:Boolean?=null,val conflictFree:Boolean?=null,val fitsAvailableTime:Boolean?=null)
@Serializable data class NextActionContext(val nowIso:String?=null,val availableMinutes:Int?=null,val evidence:List<String> = emptyList(),val candidateFacts:List<NextActionCandidate> = emptyList())
@Serializable data class NextActionRequest(val schemaVersion:String="1",val context:NextActionContext=NextActionContext(),val candidates:List<String> = emptyList())
@Serializable data class AiCapabilityResponse(val schemaVersion:String="1",val requestId:String,val result:JsonObject,val model:String)

class AiCapabilityService(private val generator:AiTextGenerator,private val json:Json=Json{ignoreUnknownKeys=false}) {
    fun naturalLanguage(r:NaturalLanguageRequest,id:String):AiCapabilityResponse { validate(r.schemaVersion,r.message);validateContext(r.context);return generate(id,naturalLanguagePrompt(r),::validateNaturalLanguage) }
    fun explanation(r:ExplanationRequest,id:String):AiCapabilityResponse { validate(r.schemaVersion,r.question);validateStringList(r.evidence,"evidence");return generate(id,"""You are the explanation layer of Super Planner. Explain using ONLY supplied evidence. If evidence is insufficient, explicitly say so and use LOW confidence. evidenceUsed must contain only exact supplied entries. If evidence conflicts, explicitly acknowledge the conflict. Return ONLY JSON: {"explanation":string,"evidenceUsed":[string],"confidence":"HIGH|MEDIUM|LOW"}. Question: ${json.encodeToString(ExplanationRequest.serializer(),r)}""",{validateExplanation(it,r.evidence)}) }
    fun command(r:CommandRequest,id:String):AiCapabilityResponse { validate(r.schemaVersion,r.message);validateContext(r.context);return generate(id,"""Convert the request into exactly one known PlanningCommand. Never execute, calculate routes, access databases, or invent facts. Commands: MARK_DELAYED, CANCEL_ACTIVITY, CREATE_ACTIVITY_DRAFT, CHANGE_ACTIVITY, REORGANIZE_DAY, MISSING_INFORMATION. Unknown or ambiguous requests must use MISSING_INFORMATION. Return ONLY JSON: {"commandType":"...","requiresConfirmation":true,"payload":{},"explanation":string}. Request: ${json.encodeToString(CommandRequest.serializer(),r)}""",::validateCommand) }
    fun insight(r:InsightRequest,id:String):AiCapabilityResponse { require(r.schemaVersion=="1"){"unsupported schemaVersion"};require(r.sampleSize>=0);validateStringList(r.evidence,"evidence");return generate(id,"""Interpret only supplied evidence. Do not invent statistics or treat small samples as facts. Return ONLY JSON: {"insights":[{"title":string,"description":string,"evidence":[string],"confidence":"HIGH|MEDIUM|LOW"}],"recommendations":[string]}. Request: ${json.encodeToString(InsightRequest.serializer(),r)}""",{validateInsights(it,r.evidence,r.sampleSize)}) }
    fun preference(r:PreferenceRequest,id:String):AiCapabilityResponse { require(r.schemaVersion=="1"){"unsupported schemaVersion"};validateStringList(r.observations,"observations");return generate(id,"""Infer candidate planning preferences only from supplied observations. One isolated observation is insufficient. Do not persist or apply preferences. Return ONLY JSON: {"preferences":[{"preference":string,"evidence":[string],"confidence":"HIGH|MEDIUM|LOW"}]}. Observations: ${json.encodeToString(PreferenceRequest.serializer(),r)}""",{validatePreferences(it,r.observations)}) }
    fun scenario(r:ScenarioRequest,id:String):AiCapabilityResponse { validate(r.schemaVersion,r.question);validateContext(r.context);return generate(id,"""Interpret a hypothetical planning scenario only. Never mutate the real plan. Separate hypothetical changes from supplied real context, mark every change hypothetical and list inferred fields. Ambiguous requests must set requiresClarification=true. Return ONLY JSON: {"scenario":string,"changes":[{"field":string,"from":string|null,"to":string,"hypothetical":true}],"assumptions":[string],"inferredFields":[string],"requiresClarification":boolean}. Request: ${json.encodeToString(ScenarioRequest.serializer(),r)}""",::validateScenario) }
    fun nextAction(r:NextActionRequest,id:String):AiCapabilityResponse { require(r.schemaVersion=="1"){"unsupported schemaVersion"};validateNextActionRequest(r);return generate(id,"""Recommend a next action only from the supplied candidate list. Never invent or calculate planning facts. Respect supplied duration, preparation, travel, priority, dependencies and conflict status. fitsAvailableTime is a domain-supplied feasibility fact; do not recompute it. dependenciesSatisfied=false or conflictFree=false means the candidate is not eligible. If context is insufficient, return recommendedAction=null, confidence=LOW, requiresClarification=true and explain missing context in uncertainty. Evidence must contain only exact supplied context evidence. Suggestions are not execution. Return ONLY JSON: {"recommendedAction":"candidate id or null","reason":string,"evidence":[string],"alternatives":["candidate ids"],"confidence":"HIGH|MEDIUM|LOW","uncertainty":[string],"requiresClarification":boolean}. Alternatives at most two. Request: ${json.encodeToString(NextActionRequest.serializer(),r)}""",{validateNextAction(it,r)}) }

    private fun validate(v:String,m:String){require(v=="1"){"unsupported schemaVersion"};require(m.isNotBlank()){ "message must not be blank" };require(m.length<=MAX_INPUT_LENGTH)}
    private fun validateContext(c:AiProposalContext){c.nowIso?.let{require(it.length<=MAX_INPUT_LENGTH)};c.activeActivityId?.let{require(it.length<=MAX_INPUT_LENGTH)};validateStringList(c.minimalRouteFacts,"minimalRouteFacts")}
    private fun validateStringList(v:List<String>,n:String){require(v.size<=MAX_LIST_ITEMS){"$n has too many items"};v.forEach{require(it.length<=MAX_INPUT_LENGTH){"$n contains an oversized item"}}}
    private fun generate(id:String,prompt:String,validator:(JsonObject)->Unit):AiCapabilityResponse { val result=try{json.decodeFromString<JsonObject>(cleanJson(generator.generate(prompt)))}catch(e:Exception){throw InvalidAiCapabilityException("AI returned invalid JSON",e)};require(result.isNotEmpty());try{validator(result)}catch(e:IllegalArgumentException){throw InvalidAiCapabilityException("AI returned an invalid capability response",e)};return AiCapabilityResponse(requestId=id,result=result,model=generator.modelName) }
    private fun validateNaturalLanguage(r:JsonObject){requireEnum(r,"commandType",setOf("CREATE_ACTIVITY_DRAFT","MISSING_INFORMATION"));requireString(r,"explanation");requireBoolean(r,"requiresConfirmation");requireObject(r,"payload");requireStringArray(r,"inferredFields");requireStringArray(r,"missingFields");if((r["commandType"] as JsonPrimitive).content=="CREATE_ACTIVITY_DRAFT")require(r["requiresConfirmation"].toString()=="true")}
    private fun validateExplanation(r:JsonObject,s:List<String>){requireString(r,"explanation");requireStringArray(r,"evidenceUsed");requireEnum(r,"confidence",CONFIDENCE);val u=(r["evidenceUsed"] as JsonArray).map{(it as JsonPrimitive).content};require(u.all{s.contains(it)});if(s.isEmpty()){require(u.isEmpty());require((r["confidence"] as JsonPrimitive).content=="LOW")}}
    private fun validateCommand(r:JsonObject){requireEnum(r,"commandType",COMMANDS);requireBoolean(r,"requiresConfirmation");requireObject(r,"payload");requireString(r,"explanation");val c=(r["commandType"] as JsonPrimitive).content;if(c!="MISSING_INFORMATION")require(r["requiresConfirmation"].toString()=="true");validateCommandPayload(c,r["payload"] as JsonObject)}
    private fun validateCommandPayload(c:String,p:JsonObject){
        when(c){
            "MARK_DELAYED" -> {requireExactKeys(p,setOf("activityId","delayMinutes"));requireString(p,"activityId");requirePositiveInteger(p,"delayMinutes")}
            "CANCEL_ACTIVITY" -> {requireExactKeys(p,setOf("activityId"));requireString(p,"activityId")}
            "CREATE_ACTIVITY_DRAFT" -> {require(p.containsKey("title"));requireString(p,"title");val a=setOf("title","date","startTime","durationMinutes","recurrence");require(p.keys.all{it in a});listOf("date","startTime","recurrence").forEach{if(p.containsKey(it))requireString(p,it)};if(p.containsKey("durationMinutes"))requirePositiveInteger(p,"durationMinutes")}
            "CHANGE_ACTIVITY" -> {requireExactKeys(p,setOf("activityId","changes"));requireString(p,"activityId");require((p["changes"] as? JsonObject)?.isNotEmpty()==true)}
            "REORGANIZE_DAY" -> {require(p.isNotEmpty());val a=setOf("date","reason","constraints");require(p.keys.all{it in a});if(p.containsKey("date"))requireString(p,"date");if(p.containsKey("reason"))requireString(p,"reason");if(p.containsKey("constraints"))requireStringArray(p,"constraints")}
            "MISSING_INFORMATION" -> {requireExactKeys(p,setOf("missingFields"));requireStringArray(p,"missingFields");require((p["missingFields"] as JsonArray).isNotEmpty())}
            else -> throw IllegalArgumentException("unsupported command")
        }
    }
    private fun validateInsights(r:JsonObject,s:List<String>,n:Int){val a=r["insights"] as? JsonArray ?: throw IllegalArgumentException();a.forEach{val o=it as? JsonObject ?: throw IllegalArgumentException();requireString(o,"title");requireString(o,"description");requireStringArray(o,"evidence");requireEnum(o,"confidence",CONFIDENCE);val e=(o["evidence"] as JsonArray).map{(it as JsonPrimitive).content};require(e.all{s.contains(it)});if(n<MIN_INSIGHT_SAMPLE_SIZE)require((o["confidence"] as JsonPrimitive).content=="LOW")};requireStringArray(r,"recommendations")}
    private fun validatePreferences(r:JsonObject,s:List<String>){val a=r["preferences"] as? JsonArray ?: throw IllegalArgumentException();a.forEach{val o=it as? JsonObject ?: throw IllegalArgumentException();requireString(o,"preference");requireStringArray(o,"evidence");requireEnum(o,"confidence",CONFIDENCE);val e=(o["evidence"] as JsonArray).map{(it as JsonPrimitive).content};require(e.isNotEmpty());require(e.all{s.contains(it)});if(s.size<MIN_PREFERENCE_SAMPLE_SIZE)require((o["confidence"] as JsonPrimitive).content=="LOW")}}
    private fun validateScenario(r:JsonObject){requireString(r,"scenario");requireStringArray(r,"assumptions");requireStringArray(r,"inferredFields");requireBoolean(r,"requiresClarification");val a=r["changes"] as? JsonArray ?: throw IllegalArgumentException();a.forEach{val o=it as? JsonObject ?: throw IllegalArgumentException();requireString(o,"field");requireString(o,"to");requireBoolean(o,"hypothetical");require(o["hypothetical"].toString()=="true");o["from"]?.let{v->require(v is JsonPrimitive&&v.isString)}}}
    private fun validateNextActionRequest(r:NextActionRequest){require(r.candidates.size<=MAX_LIST_ITEMS);require(r.candidates.distinct().size==r.candidates.size);validateStringList(r.candidates,"candidates");r.context.nowIso?.let{require(it.length<=MAX_INPUT_LENGTH)};r.context.availableMinutes?.let{require(it>=0)};validateStringList(r.context.evidence,"evidence");require(r.context.candidateFacts.size<=MAX_LIST_ITEMS);r.context.candidateFacts.forEach{f->require(f.id.isNotBlank()&&f.id.length<=MAX_INPUT_LENGTH);require(f.id in r.candidates);f.durationMinutes?.let{require(it>0)};f.preparationMinutes?.let{require(it>=0)};f.travelMinutes?.let{require(it>=0)};f.priority?.let{require(it>=0)}};require(r.context.candidateFacts.map{it.id}.distinct().size==r.context.candidateFacts.size)}
    private fun validateNextAction(r:JsonObject,q:NextActionRequest){val recommended=r["recommendedAction"].let{v->when(v){null,JsonNull->null;is JsonPrimitive->if(v.isString)v.content else null;else->throw IllegalArgumentException()}};require(recommended==null||recommended in q.candidates);requireString(r,"reason");val structured=r.containsKey("evidence")||r.containsKey("uncertainty")||r.containsKey("requiresClarification");if(structured){requireStringArray(r,"evidence");requireStringArray(r,"uncertainty");requireBoolean(r,"requiresClarification");val e=(r["evidence"] as JsonArray).map{(it as JsonPrimitive).content};require(e.all{it in q.context.evidence})};requireEnum(r,"confidence",CONFIDENCE);val a=r["alternatives"] as? JsonArray ?: throw IllegalArgumentException();require(a.size<=2);require(a.all{it is JsonPrimitive&&it.isString&&it.content in q.candidates});require(a.distinct().size==a.size);require(recommended !in a.map{(it as JsonPrimitive).content});val facts=q.context.candidateFacts.associateBy{it.id};fun eligible(id:String)=facts[id]?.let{it.dependenciesSatisfied!=false&&it.conflictFree!=false&&it.fitsAvailableTime!=false}?:true;if(recommended!=null)require(eligible(recommended));a.forEach{require(eligible((it as JsonPrimitive).content))};val hasContext=q.context.nowIso!=null||q.context.availableMinutes!=null||q.context.evidence.isNotEmpty()||q.context.candidateFacts.isNotEmpty();if(structured&&(!hasContext||q.candidates.isEmpty())){require(recommended==null);require((r["confidence"] as JsonPrimitive).content=="LOW");require((r["requiresClarification"] as JsonPrimitive).content=="true")};if(structured&&recommended==null)require((r["requiresClarification"] as JsonPrimitive).content=="true")}
    private fun requireString(r:JsonObject,k:String){val v=r[k] as? JsonPrimitive;require(v!=null&&v.isString&&v.content.isNotBlank())}
    private fun requireBoolean(r:JsonObject,k:String){val v=r[k] as? JsonPrimitive;require(v!=null&&!v.isString&&v.content in setOf("true","false"))}
    private fun requirePositiveInteger(r:JsonObject,k:String){val v=r[k] as? JsonPrimitive;require(v!=null&&!v.isString&&v.content.toIntOrNull()?.let{it>0}==true)}
    private fun requireObject(r:JsonObject,k:String){require(r[k] is JsonObject)}
    private fun requireExactKeys(p:JsonObject,e:Set<String>){require(p.keys==e)}
    private fun requireStringArray(r:JsonObject,k:String){val v=r[k];require(v is JsonArray&&v.size<=MAX_LIST_ITEMS&&v.all{it is JsonPrimitive&&it.isString&&it.content.length<=MAX_INPUT_LENGTH})}
    private fun requireEnum(r:JsonObject,k:String,a:Set<String>){val v=r[k] as? JsonPrimitive;require(v!=null&&v.isString&&v.content in a)}
    private fun cleanJson(raw:String)=raw.trim().removePrefix("```json").removePrefix("```").removeSuffix("```").trim()
    private fun naturalLanguagePrompt(r:NaturalLanguageRequest)="""Interpret planning intent without execution or persistence. Return ONLY JSON with commandType, explanation, requiresConfirmation, payload, inferredFields and missingFields. Use only CREATE_ACTIVITY_DRAFT or MISSING_INFORMATION; ambiguity must be explicit. Request: ${json.encodeToString(NaturalLanguageRequest.serializer(),r)}"""
    companion object{private const val MAX_INPUT_LENGTH=12_000;private const val MAX_LIST_ITEMS=100;private const val MIN_INSIGHT_SAMPLE_SIZE=3;private const val MIN_PREFERENCE_SAMPLE_SIZE=3;private val COMMANDS=setOf("MARK_DELAYED","CANCEL_ACTIVITY","CREATE_ACTIVITY_DRAFT","CHANGE_ACTIVITY","REORGANIZE_DAY","MISSING_INFORMATION");private val CONFIDENCE=setOf("HIGH","MEDIUM","LOW")}
}
